GVL: Added popup with error message for unsupported qr code format (P…
gini/gini-vision-lib-ios pull request #450
Opened 2021-06-16 18:45 UTC by zladzeyka

…IA-1553)

### Description
added popup for unsupported qr code

### How to test
https://ginis.atlassian.net/browse/PIA-1068

### Merging
Automatic

### Issues

2021-06-17 15:48 UTC, a-szotyori approved these changes
I found a bug while testing and while at it I also implemented a fix for it. 😄

2021-06-17 16:04 UTC, a-szotyori commented
We need to add color configuration for the red color.

2021-06-17 16:17 UTC, zladzeyka reviewed
Looks good!

2021-06-17 16:51 UTC, a-szotyori requested changes

2021-06-17 16:51 UTC, a-szotyori commented on GiniVision/Classes/Core/Screens/Camera/CameraViewController.swift
> +        newQRCodePopup.qrText.textColor = giniConfiguration.unsupportedQrCodePopupColor
In the `QRCodeDetectedPopupView` we are using a `GiniColor` and our `UIColor.from()` extension:
```
qrText.textColor = UIColor.from(giniColor: giniConfiguration.qrCodePopupTextColor)
``` 

We should do it the same here as well and then also rename it to `unsupportedQrCodePopupTextColor`.

```suggestion
        newQRCodePopup.qrText.textColor = UIColor.from(giniColor: giniConfiguration.unsupportedQrCodePopupTextColor)
```

2021-06-17 16:51 UTC, a-szotyori commented on GiniVision/Classes/Core/Screens/Camera/CameraViewController.swift
> +        newQRCodePopup.proceedButton.setTitleColor(giniConfiguration.unsupportedQrCodePopupColor, for: .normal)
Also then we should add an `unsupportedQrCodePopupButtonColor` as well to be analogous with `qrCodePopupButtonColor`. And also add the same highlighted state color as for the normal popup.
```suggestion
        newQRCodePopup.proceedButton.setTitleColor(giniConfiguration.unsupportedQrCodePopupButtonColor, for: .normal)
        newQRCodePopup.proceedButton.setTitleColor(giniConfiguration.unsupportedQrCodePopupButtonColor.withAlphaComponent(0.5),
                                                   for: .highlighted)
```

2021-06-18 10:23 UTC, a-szotyori commented on GiniVision/Classes/Core/Screens/Camera/CameraViewController.swift
> +        newQRCodePopup.proceedButton.setTitleColor(giniConfiguration.unsupportedQrCodePopupButtonColor, for: .normal)
Also need to set the color for the highlighted state (same as the `QRCodeDetectedPopupView` does on line 73):
```suggestion
        newQRCodePopup.proceedButton.setTitleColor(giniConfiguration.unsupportedQrCodePopupButtonColor, for: .normal)
newQRCodePopup.proceedButton.setTitleColor(giniConfiguration.unsupportedQrCodePopupButtonColor.withAlphaComponent(0.5),                                                   for: .highlighted)
```

2021-06-18 11:02 UTC, a-szotyori approved these changes

2021-06-18 11:22 UTC, merged